 # Day 2 – NumPy & Pandas
 **Week 3 – Python, Pandas & Exploratory Data Analysis**
 ## Topics Covered
- NumPy arrays, operations, vectorization, indexing
- Pandas Series & DataFrames
- Reading CSV, Excel, JSON
- Selecting, filtering, sorting
- GroupBy & aggregation
- Merging & concatenation

## 1. NumPy Arrays

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr)
print(type(arr))
print(arr.shape)

[10 20 30 40 50]
<class 'numpy.ndarray'>
(5,)

## 2. Array Operations & Vectorization

In [3]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2 + 10)

[11 12 13 14 15]

## 3. Indexing

In [4]:
print(arr2[0])

1

In [5]:
print(arr2[-1])

5

In [6]:
print(arr2[1:4])

[2 3 4]

In [7]:
print(arr2[arr2 > 2])

[3 4 5]

## 4. Pandas Series

In [9]:
import pandas as pd
prices = pd.Series([80000, 1500, 3000, 20000],
index=['Laptop', 'Mouse', 'Keyboard', 'Monitor'])
print(prices)
print(prices['Laptop'])

Laptop      80000
Mouse        1500
Keyboard     3000
Monitor     20000
dtype: int64
80000

## 5. Pandas DataFrames

In [10]:
data = { 'product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor'],
'price': [80000, 1500, 3000, 20000],
'category': ['Electronics', 'Accessories', 'Accessories', 'Electronics'] }
df = pd.DataFrame(data)
print(df)
df.head()

    product  price     category
0    Laptop  80000  Electronics
1     Mouse   1500  Accessories
2  Keyboard   3000  Accessories
3   Monitor  20000  Electronics

    product  price     category
0    Laptop  80000  Electronics
1     Mouse   1500  Accessories
2  Keyboard   3000  Accessories
3   Monitor  20000  Electronics

## 6. Reading a Real-World Dataset (CSV)

In [11]:
sales_df = pd.read_csv('sales_data.csv')

In [12]:
print(sales_df.shape)

(10, 8)

In [13]:
sales_df.head()

,order_id,customer_name,city,product,category,quantity,price,order_date
0,1,Ali,Lahore,Laptop,Electronics,1,80000,2025-01-10
1,2,Sara,Karachi,Mouse,Accessories,2,1500,2025-01-12
2,3,Usman,Lahore,Keyboard,Accessories,1,3000,2025-01-15
3,4,Ayesha,Islamabad,Monitor,Electronics,1,20000,2025-01-18
4,5,Bilal,Lahore,Laptop,Electronics,1,80000,2025-01-20

In [14]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       10 non-null     int64
 1   customer_name  10 non-null     object
 2   city           10 non-null     object
 3   product        10 non-null     object
 4   category       10 non-null     object
 5   quantity       10 non-null     int64
 6   price          10 non-null     int64
 7   order_date     10 non-null     object
dtypes: int64(3), object(5)
memory usage: 772.0+ bytes

## 7. Reading Excel and JSON